### ISSUE TITLE
README incorrect?

### ISSUE THREAD

**Issue by alistairholt** [miragejs/graphql#10]
Is the README correct?

`npm i miragejs @miragejs/graphql`.

```javascript
import { createGraphQLHandler } from 'miragejs-graphql'
```

`Module not found: Error: Can't resolve 'miragejs-graphql'`?

**Comment by alistairholt** [comment]
I had to use `import { createGraphQLHandler } from '@miragejs/graphql'` to get it working.

**Comment by jneurock** [comment]
Yeah, you're right, Sounds like it needs an update. Thanks!!

**Comment by jneurock** [comment]
Should be good now
