### ISSUE TITLE
Support for object union types

### ISSUE THREAD

**Issue by kdembler** [miragejs/graphql#12]
Hey there and thanks for the awesome library!

I'm running into a problem trying to use a schema with a union type. Consider the following schema:

```graphql
type Orange {
  id: ID!
  weight: Float!
}

type Apple {
  id: ID!
  radius: Float!
}

union Fruit = Orange | Apple

type Basket {
  id: ID!
  fruit: Fruit!
}

type Query {
  basket: Basket!
}
```

I'm trying to run a following query against it:

```graphql
query GetBasket {
  basket {
    id
    fruit {
      ... on Orange {
        id
        weight
      }
      ... on Apple {
        id
        radius
      }
    }
  }
}
```

However, when executing it, I run into an error: `Abstract type "Fruit" must resolve to an Object type at runtime for field "Basket.fruit" with value [{ id: "appleID", radius: 5, __typename: "Apple" }], received "undefined". Either the "Fruit" type should provide a "resolveType" function or each possible type should provide an "isTypeOf" function.`

As can be seen in the error message, the object contains `__typename` field so I'd expect the server to be able to determine the type.

I'm not sure whether that's an issue with the library or me using GraphQL incorrectly but I've tried everything that came to my mind.

**Comment by jneurock** [comment]
Hey, thanks for the feedback!

At first glance, I think the issue is that the `Basket` type expects a singular fruit. I assume it would be more like a list of fruit, `fruit: [Fruit]`, which should work with a union type.

**Comment by kdembler** [comment]
List of issues would actually make more sense in a basket, maybe it was a bad choice of an example type on my part. 😅 

The problem still stands - I'm looking to have a single value of union type, just like in the example.

**Comment by jneurock** [comment]
No worries on the example. The same still applies; though, union types are intended for lists, as I understand it.

**Comment by kdembler** [comment]
Ah, I've missed that this was your point.

However, take a look at https://spec.graphql.org/June2018/#sec-Unions. The union definition doesn't have anything to do with a list and the example given in the spec doesn't use one.

**Comment by jneurock** [comment]
I see. Thanks for pointing that out!! I looked for something like this when implementing the automatic union type resolution and I couldn't find it 😅  It was a question on my mind, whether or not a union type could be resolved for a single record.

This means that Mirage GraphQL makes the wrong assumption here and can't automatically resolve union types this way, for now. We'll have to put in a bug fix.

To get around this, you can supply your own resolver for the field. The resulting record will just need the `__typename` field populated and you should be able to keep going. I'm happy to help you with the resolver, if you'd like. You can join Mirage's Discord server: https://discord.gg/8PxR2E for more direct conversations. There's even a #graphql channel.

**Comment by jneurock** [comment]
Here's an example resolver:
```javascript
import { mirageGraphQLFieldResolver } from "@miragejs/graphql"

const graphQLHandler = createGraphQLHandler(schema, this.schema, {
  resolvers: {
    Basket: {
      fruit() {
        const [fruit] = mirageGraphQLFieldResolver(...arguments);

        return fruit;
      }
    }
  }
})
```

**Comment by jneurock** [comment]
Just to capture the necessary notes for fixing the bug:
* Mirage GraphQL almost has it right... it gets the right record but always returns a list.
* We need to check the return type of the field and make sure we don't just assume union type fields should resolve to a list.
