### ISSUE TITLE
Typescript error: /lib/resolvers/mirage.js v0.1.8

### ISSUE THREAD

**Issue by gfmartinez** [miragejs/graphql#25]
v0.1.8
[https://github.com/miragejs/graphql/blob/main/lib/resolvers/mirage.js](https://github.com/miragejs/graphql/blob/main/lib/resolvers/mirage.js)
compiles in node_modules with an error.

<img width="931" alt="Screen Shot 2020-11-04 at 11 18 21 AM" src="https://user-images.githubusercontent.com/14170693/98136960-778fc700-1e8f-11eb-8c1a-0f74df1ef016.png">

**Comment by jneurock** [comment]
Thanks for reporting this. Since I'm not a TypeScript user or expert by any means, could you tell me what kind of problems this causes? Also, would be happy to know if you see a quick fix. Thanks!

**Comment by gfmartinez** [comment]
@jneurock I put in a PR to fix the compile errors. Was in several of the resolver compiled ts files:
[https://github.com/miragejs/graphql/pull/26](https://github.com/miragejs/graphql/pull/26)

**Comment by kevinmook** [comment]
I just wanted to +1 this issue and gfmartinez's fix. With the incorrect types, the typescript compiler is erroring so any typescript project that uses this lib won't be able to compile.

Thanks for the lib, and gfmartinez for this fix!

**Comment by jneurock** [comment]
Thanks for the issue, the PR and the helpful, contextual comments!! I'll take a look at the PR as soon as I can.
