### ISSUE TITLE
Missing CommonJS distribution

### ISSUE THREAD

**Issue by 2WheelCoder** [miragejs/graphql#3]
Really excited about this package, unfortunately I have been unable to get it to work in my Next.js app because it is distributed as ES2015 modules instead of CommonJS. Since many developers are not transpiling their node_modules folders I believe its best practice to distribute a CommonJS format so that it works in a typical Node environment without any additional work by the user. The miragejs package has an example of offering both. If you look at their package.json it lists:

```
"main": "dist/mirage-cjs.js",
"module": "dist/mirage-esm.js",
```

The error I get is:
```
import { createGraphQLHandler } from "./lib/handler";
       ^

SyntaxError: Unexpected token {
```

I took a shot at trying to transpile this using my Next.js babel settings, but wound up with this error:
`TypeError: Cannot destructure property `context` of 'undefined' or 'null'.`

Thanks for the hard work here! Can't wait to try it out.

**Comment by jneurock** [comment]
Thanks for opening the issue. I assume we'll cover this at some point soon; but in the meantime, I think you discovered and fixed the type error in your PR #4.

**Comment by jneurock** [comment]
I released version `0.1.2` with a Common JS distribution. Let me know if this works for you. Thanks!

**Comment by 2WheelCoder** [comment]
I got stuck on some issues with resolvers and had to put this down for awhile, but just upgraded to 0.1.3 and I am getting the same error as before:

```
import { createGraphQLHandler } from "./lib/handler";
       ^

SyntaxError: Unexpected token {
```

**Comment by jneurock** [comment]
🤔  That code doesn't exist in the new distribution. Does Next.js cache dependencies somewhere or is it possible you're importing Mirage GraphQL differently than `import { createGraphQLHandler } from "@miragejs/graphql"`?

**Comment by 2WheelCoder** [comment]
Ah, you know what, I had run `yarn link @miragejs/graphql` and forgot to unlink. Now it is loading. Thanks! I just have to figure out all the Mirage errors from my crazy schema.

**Comment by jneurock** [comment]
Oh, I'm glad to hear it's actually working 😅  Thanks for checking! If you get stuck on Mirage errors or just want to save some time, feel free to ping me or Sam on the Mirage Discord server.
