### ISSUE TITLE
Expose API or hooks for custom resolvers

### ISSUE THREAD

**Issue by smketterer** [miragejs/graphql#45]
It would be nice if we could reuse some of the inbuilt logic for pagination, simple field resolving, etc. as a basis for our own custom resolvers. Any chance that some of these functions could be exposed via a public API?

I'm looking to do some more advanced filtering, but in order to do so it appears that I have to implement everything else as well, which turns a seemingly small task into a seemingly big task. Another option might be to expose hooks within the resolver to allow us to e.g. filter a set of objects before pagination is applied, although this might be less robust for other use cases.

Just trying to start a discussion, I'm also willing to help with this if this fits with the goals of the project.

Not directly related to the ask above, but I would also appreciate some more advanced and/or real-world examples of custom resolvers if anyone is willing to contribute any!

**Comment by jneurock** [comment]
Hi. Thanks for the question. There should be a ton of functions from the library you can import and use in your own resolvers to make things easier. Feel free to peruse the source code of the built-in resolvers to see them. These functions are documented so there should be some explanation of what they do but we're not currently generating and publishing any documentation for them.

Let me know if you see some helpful improvements that could be made to these functions to cover your needs and feel free to reach me on the [Mirage Discord](https://discord.gg/pPsdsrn) for more collaboration.

**Comment by jneurock** [comment]
I'm closing this issue for now (because of its age) but please feel absolutely free to reopen it, if the built-in functions I described don't work for you or more discussion is needed. Suggestions for additional functionality are very welcome!
