### ISSUE TITLE
createGraphQLHandler can't deal with directives

### ISSUE THREAD

**Issue by thomasdittmar** [miragejs/graphql#46]
Hi all,

I love this library. It works so well.

I discovered a problem when I use directives in the query. Here is a simple example.

_app/gql/schema.gql_
```javascript
type Person {
  id: ID!
  key: String
  firstName: String!
  lastName: String!
}

type Query {
  allPeople: [Person]
}
```
_app/components/person.js_
```javascript
import { createServer } from "app/mirage/server";
import { request } from "graphql-request"

const server = createServer();

server.create("person", { firstName: "Mikael", lastName: "Åkerfeldt" })

export default {
  // ...other component stuff

  personQuery: `
    query Person($id: id) {
      person(id: $id) {
        id
        key @client
        firstName
        lastName
      }
    }
  `,
  getPerson(id) {
    return request("/graphql", this.personQuery, { id })
  }
}
```

In the production version my Person type does not have the `key` attribute but I `inject` it with `typePolicies` of the `ApolloClient` at the start of the app.

When I run `Mirage` with the `key @client` directive in the query I get the following error

```javascript
"message": "Unknown directive @client.",
```

My current work-around is to create a copy of the query file with the `*.e2e.ts` extension but I would rather not double-up on these files.

Is there a way to overcome that issue? Maybe with a resolver? 

Cheers,

Tom

**Comment by jneurock** [comment]
Hi Tom, I'm so glad to hear the library works well for you... most of the time 😅 


Could be that you need a custom resolver but I'd like to check how we can handle this from the library side, too.

I'll have to look into this issue more deeply. I might start with adding a test that includes a query with a directive. It's possible that this library just isn't friendly to directives. I'm pretty sure I didn't include any directives in the tests so they may be entirely unsupported 🙈

**Comment by thomasdittmar** [comment]
Hi @jneurock,

Thank you for looking into that. 

Perhaps this piece of information will help you.

I already have custom resolvers setup. Something like that

```javascript
getPerson(obj: any, args: any, context: any, info: any) {
    console.log(JSON.stringify(info.schema._directives))
    return mirageGraphQLFieldResolver(obj, args, context, info)
  }
```

When I console log the schema directives I get the following result

```javascript
["@include","@skip","@deprecated","@specifiedBy"]
```

Perhaps, that are the ones that are actually accepted and any custom one won't be recognised? 

Cheers,

Tom

**Comment by jneurock** [comment]
Closing this issue for now but please feel free to reopen it, if need be. Thanks!
