### ISSUE TITLE
Possible to mix in custom resolvers?

### ISSUE THREAD

**Issue by madebyaaron** [miragejs/graphql#5]
Loving this package so far and all the automatic crud mutations you get out of the box. Amazing job!

Aside from the basic crud mutations, i do have some mutations that need custom logic (password reset, signup activation etc). Is this possible and if so, how do I go about accessing the mirage db from within them resolvers?

Thanks!

**Comment by jneurock** [comment]
Hey, thanks for the kind words! You can supply your own resolvers. See
https://github.com/miragejs/graphql#example-deleting-a-person for a small
example. If you need more, there are examples in the integration tests,
too. Please feel free to leave more questions and for more direct help,
join the Mirage Discord server:
https://discord.gg/pPsdsrn.

Take care!

**Comment by madebyaaron** [comment]
Sorry i missed this when reading the docs!
I'm looking forward to getting stuck in to using this in my project.

Thanks again
