### ISSUE TITLE
Mirage: You called server.create(<model_name>) but no model or factory was found

### ISSUE THREAD

**Issue by Freire71** [miragejs/graphql#65]
Hi @jneurock , on the following example I have 2 entities that are connected `HouseListing` and `HouseListingMedia`, when I try to create an instance of `HouseListingMedia` I get the following error: `You called server.create('houseListingMedia') but no model or factory was found.`. 

I've tried changing the capitalization but it has no effect. `houseListingMediaObject` is the content that I've tried to create the instance of `HouseListingMedia`. When I run `console.log` on the server variable I can see that `houseListingMedia` is a recognized model. Why I'm getting this error? 

I saw on unit testing that first I need to create the "child" entity, in this case `HouseListingMedia` and use the `server.create` return to create the "father", in this case `HouseListing`. When i try to createa a `HouseListing` without creating a `HouseListingMedia` it works, but I want to make this relationship work. 

I've tried adding an ID field to `HouseListingMedia` but is does not seem to be the cause. This behavior is the same for both testing and development

#### This is a fragment of my schema 
```
type HouseListingMedia {
    isPublic: Boolean!
    displayOrder: Int!
    propertyId: String!
    photoUrl: String
    thumbnailUrl: String
}

type HouseListing {
    id: ID!
    images: [HouseListingMedia]
    ...
}
```

#### Console.log on server
<img width="2242" alt="image" src="https://user-images.githubusercontent.com/26610141/216478166-b99f744f-3e9e-4be7-8ab7-eaec7015f084.png">

**Comment by jneurock** [comment]
This has to do with Mirage's use of [infelected](https://www.npmjs.com/package/inflected) and how it singularizes certain words. In this case, try `'houseListingMedium'`. See [this example](https://runkit.com/embed/1s6jq166rpm3).

**Comment by Freire71** [comment]
Thank you for being so fast! it is definitely the answer
